# Generated by Django 2.2 on 2019-04-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
